import Header from "@/components/global/Header";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Shivam's Blog",
  description: "Generated by create-t3-app",
  icons: [],
};

const inter = Inter({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={cn(inter.className, "pt-14")}>
        <Header/>
        {children}
        </body>
    </html>
  );
}
